version: '2'
services:
  bitemporal-db:
    build:
      context: ./mysql
      args:
        MYSQL_ROOT_PASSWORD: "password"
    image: bitemporal-dev-db:latest
    container_name: bitemporal-dev-db
    command: mysqld --sql_mode=""
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/db:/var/lib/mysql
    - ./mysql/log:/var/log/mysql
    environment:
      ENV: "local"
