doma.dialect: mysql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bitemporal_development?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
